### ISSUE TITLE
python3 emojis.py SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by crytion111** [opq-osc/bot_emojimix#1]
更新emoji信息的脚本里面报这个错, 我也不懂python, 作者你看看呗
python3 emojis.py
Traceback (most recent call last):
  File "emojis.py", line 235, in <module>
    update_emojis()
  File "emojis.py", line 215, in update_emojis
    for item in eval(
  File "<string>", line 215
    ];
     ^
SyntaxError: unexpected EOF while parsing

**Comment by crytion111** [comment]
![image](https://user-images.githubusercontent.com/89855591/154884625-2de4db25-f6b2-4f43-912e-0cfe4c3687b8.png)
